### PR TITLE
Update Travis CI Node 6.0 test to 6.1

### PR DESCRIPTION
**Pull request by calvinmikael**

### CODE REVIEW

**Comment by dougwilson** [comment]
Hi @calvinmikael, to make these easier to merge in, can you use the same commit messages as the rest of the Node.js version changes?

**Comment by calvinmikael** [comment]
@dougwilson Yes, I can make all the commit messages going forward "Add Travis CI tests for Node 5.11 and 6.1" or anything else you feel is descriptive.

**Comment by dougwilson** [comment]
I would like it to match that of the previous commits. `git log .travis.yml` to see what they are, please. Once you update this PR with the message, I can merge it :)

**Comment by calvinmikael** [comment]
@dougwilson Thanks for the clarification. I will update the commit message to be "build: Node.js@6.1". I'd just like to check once beforehand if you're okay with me using a git amend and force push to update this commit.

**Comment by dougwilson** [comment]
amend + force push sounds find to me :)

**Comment by calvinmikael** [comment]
Done

**Comment by calvinmikael** [comment]
Is this PR still desired or should I close and delete? Sorry.

**Pull request closed without merging**
